// PATH: src/app/layout.tsx

import type { Metadata, Viewport } from 'next'
import './globals.css'
import { PWARegister } from '@/components/PWARegister'
import { AuthProvider } from '@/components/AuthProvider'
import CookieConsent from '@/components/CookieConsent'
import { ToastProvider } from '@/components/Toast'
import { Poppins, Playfair_Display } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin', 'latin-ext'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
  display: 'swap',
})

const playfair = Playfair_Display({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-playfair',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Clientoro | Booking & Growth OS',
  description: 'AI Booking, CRM & Growth OS pro služby. Získejte více klientů, zvyšte tržby automaticky.',
  manifest: '/manifest.json',
  metadataBase: new URL('https://clientoro.pro'),
  openGraph: {
    title: 'Clientoro | AI Booking & Growth OS',
    description: 'Chytrý kalendář, který pomáhá zaplnit termíny a získat nové klienty. Online rezervace, CRM, AI insighty.',
    url: 'https://clientoro.pro',
    siteName: 'Clientoro',
    locale: 'cs_CZ',
    type: 'website',
    // OG image is auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Clientoro | AI Booking & Growth OS',
    description: 'Chytrý kalendář, který pomáhá zaplnit termíny a získat nové klienty.',
    // Twitter image is auto-generated by src/app/opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Clientoro',
  },
  formatDetection: {
    telephone: false,
  },
}

export const viewport: Viewport = {
  themeColor: '#0369a1',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html style={{ colorScheme: "light" }} lang="cs" className={`${poppins.variable} ${playfair.variable}`}>
      <head>
        <link rel="icon" href="/icons/icon.svg" type="image/svg+xml" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className="font-poppins">
        <AuthProvider>
          <ToastProvider>
            {children}
          </ToastProvider>
        </AuthProvider>
        <PWARegister />
        <CookieConsent />
      </body>
    </html>
  )
}
