// PATH: src/config/growthSteps.ts

export type StepTier = "free" | "plus" | "inspire";

export type GrowthStep = {
  id: string;
  order: number;
  icon: string;
  nameCs: string;
  nameSk: string;
  nameEn: string;
  descriptionCs: string;
  descriptionSk: string;
  descriptionEn: string;
  tier: StepTier;
  bonusCs: string;
  bonusSk: string;
  bonusEn: string;
  checkKey: string; // klic pro kontrolu splneni
};

export const soloGrowthSteps: GrowthStep[] = [
  {
    id: "solo-profile",
    order: 1,
    icon: "📋",
    nameCs: "Zakladni profil",
    nameSk: "Zakladny profil",
    nameEn: "Basic profile",
    descriptionCs: "Vyplnte jmeno, obor a lokalitu",
    descriptionSk: "Vyplnte meno, obor a lokalitu",
    descriptionEn: "Fill in name, field and location",
    tier: "free",
    bonusCs: "Profil na Inspire",
    bonusSk: "Profil na Inspire",
    bonusEn: "Profile on Inspire",
    checkKey: "hasProfile",
  },
  {
    id: "solo-services",
    order: 2,
    icon: "🛠️",
    nameCs: "Sluzby",
    nameSk: "Sluzby",
    nameEn: "Services",
    descriptionCs: "Pridejte min. 3 sluzby s cenami",
    descriptionSk: "Pridajte min. 3 sluzby s cenami",
    descriptionEn: "Add at least 3 services with prices",
    tier: "free",
    bonusCs: "Viditelnost v katalogu",
    bonusSk: "Viditelnost v katalógu",
    bonusEn: "Visibility in catalog",
    checkKey: "hasMinServices",
  },
  {
    id: "solo-availability",
    order: 3,
    icon: "📅",
    nameCs: "Pracovni doba",
    nameSk: "Pracovna doba",
    nameEn: "Working hours",
    descriptionCs: "Nastavte svou dostupnost",
    descriptionSk: "Nastavte svoju dostupnost",
    descriptionEn: "Set your availability",
    tier: "free",
    bonusCs: "Volne terminy viditelne",
    bonusSk: "Volne terminy viditelne",
    bonusEn: "Free slots visible",
    checkKey: "hasAvailability",
  },
  {
    id: "solo-photos",
    order: 4,
    icon: "📸",
    nameCs: "Fotografie",
    nameSk: "Fotografie",
    nameEn: "Photos",
    descriptionCs: "Nahrejte min. 3 fotky vasi prace",
    descriptionSk: "Nahrajte min. 3 fotky vasej prace",
    descriptionEn: "Upload at least 3 photos of your work",
    tier: "free",
    bonusCs: "Profil +40% kliku",
    bonusSk: "Profil +40% klikov",
    bonusEn: "Profile +40% clicks",
    checkKey: "hasMinPhotos",
  },
  {
    id: "solo-barter",
    order: 5,
    icon: "🤝",
    nameCs: "Barter klub",
    nameSk: "Barter klub",
    nameEn: "Barter club",
    descriptionCs: "Pridejte prvni nabidku vymeny",
    descriptionSk: "Pridajte prvu ponuku vymeny",
    descriptionEn: "Add first exchange offer",
    tier: "free",
    bonusCs: "Pristup ke komunite",
    bonusSk: "Pristup ku komunite",
    bonusEn: "Access to community",
    checkKey: "hasBarterOffer",
  },
  {
    id: "solo-first-ad",
    order: 6,
    icon: "📢",
    nameCs: "Prvni inzerat",
    nameSk: "Prvy inzerat",
    nameEn: "First listing",
    descriptionCs: "Vytvorte prvni inzerat sluzby",
    descriptionSk: "Vytvorte prvy inzerat sluzby",
    descriptionEn: "Create first service listing",
    tier: "free",
    bonusCs: "7 dni zdarma zvyrazneni",
    bonusSk: "7 dni zadarmo zvyraznenie",
    bonusEn: "7 days free highlight",
    checkKey: "hasFirstAd",
  },
  {
    id: "solo-ai-ad",
    order: 7,
    icon: "🤖",
    nameCs: "AI inzerat",
    nameSk: "AI inzerat",
    nameEn: "AI listing",
    descriptionCs: "Nechte AI vytvorit inzerat",
    descriptionSk: "Nechajte AI vytvorit inzerat",
    descriptionEn: "Let AI create a listing",
    tier: "plus",
    bonusCs: "3 varianty textu",
    bonusSk: "3 varianty textu",
    bonusEn: "3 text variants",
    checkKey: "hasAiAd",
  },
  {
    id: "solo-first-review",
    order: 8,
    icon: "⭐",
    nameCs: "Prvni hodnoceni",
    nameSk: "Prve hodnotenie",
    nameEn: "First review",
    descriptionCs: "Ziskejte 1. hodnoceni od klienta",
    descriptionSk: "Ziskajte 1. hodnotenie od klienta",
    descriptionEn: "Get first client review",
    tier: "free",
    bonusCs: "Badge Overeny",
    bonusSk: "Badge Overeny",
    bonusEn: "Verified badge",
    checkKey: "hasFirstReview",
  },
  {
    id: "solo-weekly-report",
    order: 9,
    icon: "📊",
    nameCs: "Tydenni prehled",
    nameSk: "Tyzdenný prehlad",
    nameEn: "Weekly report",
    descriptionCs: "Aktivujte tydenni report",
    descriptionSk: "Aktivujte tyzdenný report",
    descriptionEn: "Activate weekly report",
    tier: "plus",
    bonusCs: "AI doporuceni",
    bonusSk: "AI odporucania",
    bonusEn: "AI recommendations",
    checkKey: "hasWeeklyReport",
  },
  {
    id: "solo-optimization",
    order: 10,
    icon: "🎯",
    nameCs: "Optimalizace",
    nameSk: "Optimalizacia",
    nameEn: "Optimization",
    descriptionCs: "Aplikujte AI doporuceni",
    descriptionSk: "Aplikujte AI odporucania",
    descriptionEn: "Apply AI recommendations",
    tier: "plus",
    bonusCs: "+20% vytizenost",
    bonusSk: "+20% vytiazanost",
    bonusEn: "+20% utilization",
    checkKey: "hasOptimization",
  },
  {
    id: "solo-top-profile",
    order: 11,
    icon: "🏆",
    nameCs: "Top profil",
    nameSk: "Top profil",
    nameEn: "Top profile",
    descriptionCs: "5+ hodnoceni, 90%+ vyplneny profil",
    descriptionSk: "5+ hodnoteni, 90%+ vyplneny profil",
    descriptionEn: "5+ reviews, 90%+ completed profile",
    tier: "inspire",
    bonusCs: "Priorita ve vyhledavani",
    bonusSk: "Priorita vo vyhladavani",
    bonusEn: "Search priority",
    checkKey: "isTopProfile",
  },
  {
    id: "solo-inspire-leader",
    order: 12,
    icon: "👑",
    nameCs: "Inspire lidr",
    nameSk: "Inspire lider",
    nameEn: "Inspire leader",
    descriptionCs: "20+ hodnoceni, 4.5+ hvezd",
    descriptionSk: "20+ hodnoteni, 4.5+ hviezd",
    descriptionEn: "20+ reviews, 4.5+ stars",
    tier: "inspire",
    bonusCs: "Badge Inspire lidr",
    bonusSk: "Badge Inspire lider",
    bonusEn: "Inspire leader badge",
    checkKey: "isInspireLeader",
  },
];

export const proGrowthSteps: GrowthStep[] = [
  {
    id: "pro-profile",
    order: 1,
    icon: "🏢",
    nameCs: "Firemni profil",
    nameSk: "Firemny profil",
    nameEn: "Company profile",
    descriptionCs: "Vyplnte nazev firmy, ICO, lokalitu",
    descriptionSk: "Vyplnte nazov firmy, ICO, lokalitu",
    descriptionEn: "Fill in company name, ID, location",
    tier: "free",
    bonusCs: "Profil na Inspire",
    bonusSk: "Profil na Inspire",
    bonusEn: "Profile on Inspire",
    checkKey: "hasCompanyProfile",
  },
  {
    id: "pro-employees",
    order: 2,
    icon: "👥",
    nameCs: "Zamestnanci",
    nameSk: "Zamestnanci",
    nameEn: "Employees",
    descriptionCs: "Pridejte min. 2 zamestnance",
    descriptionSk: "Pridajte min. 2 zamestnancov",
    descriptionEn: "Add at least 2 employees",
    tier: "free",
    bonusCs: "Kalendar pro tym",
    bonusSk: "Kalendar pre tym",
    bonusEn: "Team calendar",
    checkKey: "hasMinEmployees",
  },
  {
    id: "pro-services",
    order: 3,
    icon: "🛠️",
    nameCs: "Sluzby",
    nameSk: "Sluzby",
    nameEn: "Services",
    descriptionCs: "Pridejte min. 5 sluzeb s cenami a delkou",
    descriptionSk: "Pridajte min. 5 sluzieb s cenami a dlzkou",
    descriptionEn: "Add at least 5 services with prices and duration",
    tier: "free",
    bonusCs: "Viditelnost v katalogu",
    bonusSk: "Viditelnost v katalogu",
    bonusEn: "Catalog visibility",
    checkKey: "hasMinServices",
  },
  {
    id: "pro-availability",
    order: 4,
    icon: "📅",
    nameCs: "Pracovni doba tymu",
    nameSk: "Pracovna doba tymu",
    nameEn: "Team working hours",
    descriptionCs: "Nastavte dostupnost celeho tymu",
    descriptionSk: "Nastavte dostupnost celeho tymu",
    descriptionEn: "Set availability for entire team",
    tier: "free",
    bonusCs: "Volne terminy viditelne",
    bonusSk: "Volne terminy viditelne",
    bonusEn: "Free slots visible",
    checkKey: "hasTeamAvailability",
  },
  {
    id: "pro-photos",
    order: 5,
    icon: "📸",
    nameCs: "Fotogalerie",
    nameSk: "Fotogaleria",
    nameEn: "Photo gallery",
    descriptionCs: "Nahrejte min. 5 fotek firmy/prace",
    descriptionSk: "Nahrajte min. 5 fotiek firmy/prace",
    descriptionEn: "Upload at least 5 company/work photos",
    tier: "free",
    bonusCs: "Profil +50% kliku",
    bonusSk: "Profil +50% klikov",
    bonusEn: "Profile +50% clicks",
    checkKey: "hasMinPhotos",
  },
  {
    id: "pro-first-ad",
    order: 6,
    icon: "📢",
    nameCs: "Prvni inzerat",
    nameSk: "Prvy inzerat",
    nameEn: "First listing",
    descriptionCs: "Vytvorte firemni inzerat",
    descriptionSk: "Vytvorte firemny inzerat",
    descriptionEn: "Create company listing",
    tier: "free",
    bonusCs: "7 dni zdarma zvyrazneni",
    bonusSk: "7 dni zadarmo zvyraznenie",
    bonusEn: "7 days free highlight",
    checkKey: "hasFirstAd",
  },
  {
    id: "pro-ai-ads",
    order: 7,
    icon: "🤖",
    nameCs: "AI inzeraty",
    nameSk: "AI inzeraty",
    nameEn: "AI listings",
    descriptionCs: "Generovani inzeratu pomoci AI",
    descriptionSk: "Generovanie inzeratov pomocou AI",
    descriptionEn: "AI-generated listings",
    tier: "plus",
    bonusCs: "10 generovani mesicne",
    bonusSk: "10 generovani mesacne",
    bonusEn: "10 generations monthly",
    checkKey: "hasAiAds",
  },
  {
    id: "pro-team-analytics",
    order: 8,
    icon: "📊",
    nameCs: "Analytika tymu",
    nameSk: "Analytika tymu",
    nameEn: "Team analytics",
    descriptionCs: "Aktivujte vykonnostni prehledy",
    descriptionSk: "Aktivujte vykonnostne prehlady",
    descriptionEn: "Activate performance reports",
    tier: "plus",
    bonusCs: "Kdo vydelava nejvic",
    bonusSk: "Kto zaraba najviac",
    bonusEn: "Top earners",
    checkKey: "hasTeamAnalytics",
  },
  {
    id: "pro-ai-recommendations",
    order: 9,
    icon: "🧠",
    nameCs: "AI doporuceni",
    nameSk: "AI odporucania",
    nameEn: "AI recommendations",
    descriptionCs: "Aktivujte chytre navrhy",
    descriptionSk: "Aktivujte chytre navrhy",
    descriptionEn: "Activate smart suggestions",
    tier: "plus",
    bonusCs: "Uterky slabsi - nabidnete akci",
    bonusSk: "Utorky slabsie - ponuknite akciu",
    bonusEn: "Tuesdays weak - offer promotion",
    checkKey: "hasAiRecommendations",
  },
  {
    id: "pro-reviews",
    order: 10,
    icon: "⭐",
    nameCs: "Hodnoceni firmy",
    nameSk: "Hodnotenie firmy",
    nameEn: "Company reviews",
    descriptionCs: "Ziskejte 5+ hodnoceni",
    descriptionSk: "Ziskajte 5+ hodnoteni",
    descriptionEn: "Get 5+ reviews",
    tier: "free",
    bonusCs: "Badge Overena firma",
    bonusSk: "Badge Overena firma",
    bonusEn: "Verified company badge",
    checkKey: "hasMinReviews",
  },
  {
    id: "pro-growth-plan",
    order: 11,
    icon: "📈",
    nameCs: "Rustovy plan",
    nameSk: "Rastovy plan",
    nameEn: "Growth plan",
    descriptionCs: "AI vytvori mesicni plan rustu",
    descriptionSk: "AI vytvori mesacny plan rastu",
    descriptionEn: "AI creates monthly growth plan",
    tier: "inspire",
    bonusCs: "Personalizovana strategie",
    bonusSk: "Personalizovana strategia",
    bonusEn: "Personalized strategy",
    checkKey: "hasGrowthPlan",
  },
  {
    id: "pro-multi-branch",
    order: 12,
    icon: "🏆",
    nameCs: "Multi-branch",
    nameSk: "Multi-branch",
    nameEn: "Multi-branch",
    descriptionCs: "Pridejte druhou pobocku",
    descriptionSk: "Pridajte druhu pobocku",
    descriptionEn: "Add second branch",
    tier: "inspire",
    bonusCs: "Sprava vice pobocek",
    bonusSk: "Sprava viac pobociek",
    bonusEn: "Multi-branch management",
    checkKey: "hasMultiBranch",
  },
  {
    id: "pro-inspire-company",
    order: 13,
    icon: "👑",
    nameCs: "Inspire firma",
    nameSk: "Inspire firma",
    nameEn: "Inspire company",
    descriptionCs: "20+ hodnoceni, 4.5+ hvezd, 3+ zamestnanci",
    descriptionSk: "20+ hodnoteni, 4.5+ hviezd, 3+ zamestnanci",
    descriptionEn: "20+ reviews, 4.5+ stars, 3+ employees",
    tier: "inspire",
    bonusCs: "Priorita + badge Inspire firma",
    bonusSk: "Priorita + badge Inspire firma",
    bonusEn: "Priority + Inspire company badge",
    checkKey: "isInspireCompany",
  },
];

export function getStepName(step: GrowthStep, language: string): string {
  if (language === "sk") return step.nameSk;
  if (language === "en") return step.nameEn;
  return step.nameCs;
}

export function getStepDescription(step: GrowthStep, language: string): string {
  if (language === "sk") return step.descriptionSk;
  if (language === "en") return step.descriptionEn;
  return step.descriptionCs;
}

export function getStepBonus(step: GrowthStep, language: string): string {
  if (language === "sk") return step.bonusSk;
  if (language === "en") return step.bonusEn;
  return step.bonusCs;
}

export function getTierLabel(tier: StepTier, language: string): string {
  const labels: Record<StepTier, Record<string, string>> = {
    free: { cs: "Zdarma", sk: "Zadarmo", en: "Free" },
    plus: { cs: "Plus", sk: "Plus", en: "Plus" },
    inspire: { cs: "Inspire", sk: "Inspire", en: "Inspire" },
  };
  return labels[tier][language] || labels[tier].en;
}

export function getTierColor(tier: StepTier): { bg: string; text: string; border: string } {
  const colors: Record<StepTier, { bg: string; text: string; border: string }> = {
    free: { bg: "#f0fdf4", text: "#15803d", border: "#22c55e" },
    plus: { bg: "#eff6ff", text: "#1d4ed8", border: "#3b82f6" },
    inspire: { bg: "#faf5ff", text: "#7c3aed", border: "#8b5cf6" },
  };
  return colors[tier];
}
